
[tasks.build-cli-package]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = ["twackup-cli"] }
run_task = { name = "create-package", fork = true }

[tasks.build-all]
workspace = false
dependencies = ["test", "build-cli-package"]
