target "Twackup" do
  platform :ios, "14.0"
  use_frameworks!

  pod "SDWebImage"

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete "IPHONEOS_DEPLOYMENT_TARGET"
      end
    end
  end
end
